name: Descarga Dólares Diaria

on:
  schedule:
    - cron: '0 3 * * *'  # Corre todos los días a medianoche en Buenos Aires (UTC-3)
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install requests pandas

      - name: Run Scraper
        run: python dolares.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Datos/
          git commit -m "Automated data update [$(date)]" || echo "No changes to commit"
          git push
